#ifndef __ROOT_HOST_SDKCONFIG_H__
#define __ROOT_HOST_SDKCONFIG_H__

#define CONFIG_EVENT_BUS_SUBSCRIBER_CAPACITY 24
#define CONFIG_EVENT_BUS_UI_CALLBACK_CAPACITY 24
#define CONFIG_EVENT_BUS_UI_PAYLOAD_CAPACITY 24
#define CONFIG_EVENT_BUS_UI_PAYLOAD_SIZE 256
#define CONFIG_NV_STORAGE_BLOB_POOL_SIZE 16

#define CONFIG_APP_MANAGER_MAX_RESIDENT_APPS 8
#define CONFIG_APP_MANAGER_MAX_PAGE_INSTANCES 12
#define CONFIG_APP_MANAGER_NAV_COMMAND_CAPACITY 8
#define CONFIG_APP_MANAGER_MAILBOX_CAPACITY 12
#define CONFIG_APP_MANAGER_CONTROL_QUEUE_DEPTH 16
#define CONFIG_APP_MANAGER_CONTROL_TASK_STACK 4096

#define CONFIG_TIME_SERVICE_SYNC_WORKER_STACK 3072
#define CONFIG_WIFI_SERVICE_TASK_STACK 4096
#define CONFIG_WIFI_SERVICE_QUEUE_DEPTH 16
#define CONFIG_CONNECTIVITY_MANAGER_TASK_STACK 6144
#define CONFIG_CONNECTIVITY_MANAGER_QUEUE_DEPTH 8
#define CONFIG_PROVISIONING_SERVICE_TASK_STACK 6144
#define CONFIG_PROVISIONING_SERVICE_QUEUE_DEPTH 8
#define CONFIG_MAIN_WEATHER_SERVER_BASE_URL "https://weather.example.com"
#define CONFIG_MAIN_WEATHER_DEVICE_TOKEN "example-device-token"
#ifndef CONFIG_MAIN_PROJECT_TASK_CORE_ID
    #define CONFIG_MAIN_PROJECT_TASK_CORE_ID 0
#endif
#ifndef CONFIG_MAIN_PROJECT_TASK_AFFINITY_CPU0
    #define CONFIG_MAIN_PROJECT_TASK_AFFINITY_CPU0 0
#endif
#ifndef CONFIG_MAIN_PROJECT_TASK_AFFINITY_CPU1
    #define CONFIG_MAIN_PROJECT_TASK_AFFINITY_CPU1 0
#endif
#define CONFIG_ESP_WIFI_NVS_ENABLED 1
#define CONFIG_ESP_PROTOCOMM_SUPPORT_SECURITY_VERSION_2 1
#define CONFIG_ESP_PROTOCOMM_SUPPORT_SECURITY_PATCH_VERSION 1

#endif /* __ROOT_HOST_SDKCONFIG_H__ */
