#!/usr/bin/env python3
"""Generate sim_res_meta.h: staged file count and mmap checksum.

Checksum algorithm mirrors managed_components/espressif__esp_mmap_assets
/py_tool/spiffs_assets_gen.py: files sorted by (extension, basename),
per-file entry name.ljust(n) + size u32 + offset u32 + width u16 + height u16
followed by a 0x5A 0x5A prefix before every payload; checksum is the byte
sum modulo 0x10000 of the table plus all payload bytes.
"""

import argparse
import os
import struct
import sys


def sort_key(filename):
    _, extension = os.path.splitext(filename)
    return extension, os.path.splitext(filename)[0]


def collect(assets_dir):
    skip = {'config.json', 'res.bin', 'sim_res_meta.h', 'lvgl_image_converter'}
    names = sorted(
        (n for n in os.listdir(assets_dir)
         if os.path.isfile(os.path.join(assets_dir, n)) and n not in skip),
        key=sort_key)
    entries = []
    merged = bytearray()
    for name in names:
        path = os.path.join(assets_dir, name)
        with open(path, 'rb') as handle:
            data = handle.read()
        # The device tool leaves width/height zero for .bin/.ttf payloads.
        entries.append((name, len(merged), len(data), 0, 0))
        merged.extend(b'\x5A' * 2)
        merged.extend(data)
    return entries, merged


def build_table(entries, name_len):
    table = bytearray()
    for name, offset, size, width, height in entries:
        fixed = name.encode('utf-8').ljust(name_len, b'\0')
        table.extend(fixed)
        table.extend(struct.pack('<IIHH', size, offset, width, height))
    return table


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--assets-dir', required=True)
    parser.add_argument('--output', required=True)
    parser.add_argument('--check-res-bin', default=None,
                        help='Optional device res.bin to verify parity against')
    args = parser.parse_args()

    entries, merged = collect(args.assets_dir)
    actual_max = max((len(e[0]) for e in entries), default=15)
    name_len = (actual_max + 1 + 3) & ~3
    table = build_table(entries, name_len)
    combined = table + merged
    checksum = sum(combined) & 0xFFFF
    count = len(entries)

    if args.check_res_bin:
        with open(args.check_res_bin, 'rb') as handle:
            header = handle.read(32)
        magic, version, dev_len, dev_count, dev_sum, _ = \
            struct.unpack('<4sIIIII', header[:24])
        if magic != b'MMAP':
            print('res.bin magic mismatch', file=sys.stderr)
            return 1
        if (dev_count, dev_sum, dev_len, version) != (count, checksum, name_len, 0x00010000):
            print('res.bin parity failed: device=(%d,0x%04X,len=%d,ver=0x%08X) '
                  'sim=(%d,0x%04X,len=%d)'
                  % (dev_count, dev_sum, dev_len, version,
                     count, checksum, name_len), file=sys.stderr)
            return 1

    with open(args.output, 'w') as handle:
        handle.write('/* Generated by sim/cmake/gen_res_meta.py - do not edit. */\n')
        handle.write('#ifndef SIM_RES_META_H\n')
        handle.write('#define SIM_RES_META_H\n\n')
        handle.write('#define APP_RESOURCES_SIM_FILE_COUNT %dU\n' % count)
        handle.write('#define APP_RESOURCES_SIM_CHECKSUM   0x%04XU\n' % checksum)
        handle.write('#define APP_RESOURCES_SIM_NAME_LEN   %dU\n\n' % name_len)
        handle.write('#endif /* SIM_RES_META_H */\n')
    print('sim_res_meta: %d files checksum 0x%04X' % (count, checksum))
    return 0


if __name__ == '__main__':
    sys.exit(main())
