#ifndef __APP_RESOURCES_GENERATED_H__
#define __APP_RESOURCES_GENERATED_H__

#include "app_manager_config.h"

#define APP_RESOURCES_FILE_COUNT 1U
#define APP_RESOURCES_CHECKSUM 0x4303U
#define APP_RESOURCES_IMAGE_TABLE NULL
#define APP_RESOURCES_IMAGE_COUNT 0U

#endif /* __APP_RESOURCES_GENERATED_H__ */
